#pragma once

// Qt
#include <QCoreApplication>
#include <QDateTime>
#include <QDeadlineTimer>
#include <QDebug>
#include <QDir>
#include <QElapsedTimer>
#include <QFileInfo>
#include <QFuture>
#include <QHash>
#include <QHostAddress>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QList>
#include <QMap>
#include <QMetaObject>
#include <QNetworkCookie>
#include <QObject>
#include <QPointer>
#include <QRegularExpression>
#include <QSet>
#include <QSharedPointer>
#include <QString>
#include <QStringList>
#include <QTimer>
#include <QTranslator>
#include <QUrl>
#include <QVariant>
#include <QtContainerFwd>

// std
#include <algorithm>
#include <chrono>
#include <concepts>
#include <limits>
#include <memory>
#include <type_traits>
#include <utility>

// qbt_base
#include "base/bittorrent/addtorrentparams.h"
#include "base/bittorrent/infohash.h"
#include "base/bittorrent/session.h"
#include "base/bittorrent/torrentdescriptor.h"
#include "base/logger.h"
#include "base/net/downloadmanager.h"
#include "base/search/searchpluginmanager.h"
