version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    commit-message:
      prefix: "GHA CI"
      include: "Bump action versions"
    labels:
      - "CI"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    commit-message:
      prefix: "GHA CI"
      include:  "Bump pre-commit hook versions"
    labels:
      - "CI"
    schedule:
      interval: "monthly"
