version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    labels:
      - "CI"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    labels:
      - "CI"
    schedule:
      interval: "monthly"
