<qconf>
 <name>qbittorrent</name>
 <profile>qbittorrent.pro</profile>
 <moddir>qcm</moddir>
 <datadir/>
  <dep type='qt'>
    <required/>
  </dep>
  <dep type='qt-dbus'>
  </dep>
  <dep type='pkg-config'>
    <required/>
  </dep>
  <dep type='libtorrent-rasterbar'>
    <required/>
  </dep>
  <dep type='libboost'>
    <required/>
  </dep>
  <dep type='geoip-database'>
  </dep>
  <dep type='qtsingleapplication'>
    <required/>
  </dep>
</qconf>
