PY_FILES := `find . -maxdepth 1 -type f -name '*.py' ! -name 'socks.py' -printf '%P '`

# Show available recipes to run
default:
    just --list

# Byte-compile files
build files=PY_FILES:
    python \
        -m compileall \
        {{ files }}

# Run checks on typings
check files=PY_FILES: fetch_aux
    mypy \
        {{ files }}
    pyright \
        {{ files }}

# Fetch auxiliary files
[private]
fetch_aux:
    #!/usr/bin/sh
    if [ ! -f 'socks.pyi' ]; then
        curl -L -o socks.pyi "https://raw.githubusercontent.com/python/typeshed/refs/heads/main/stubs/PySocks/socks.pyi"
    fi

# Apply formatting
format files=PY_FILES:
    pycodestyle \
        --ignore=E265,E402 \
        --max-line-length=1000 \
        --statistics \
        {{ files }}
    just \
        --fmt \
        --unstable

# Run static analyzer
lint files=PY_FILES:
    ruff \
        check \
        {{ files }}
    pyflakes \
        {{ files }}
    bandit \
        --configfile pyproject.toml \
        {{ files }}
    pydoclint \
        {{ files }}

# Run tests
test files='tests/*.py': fetch_aux
    pytest \
        {{ files }}
