#pragma once

// Qt
#include <QBasicTimer>
#include <QBitArray>
#include <QByteArray>
#include <QByteArrayView>
#include <QCache>
#include <QChar>
#include <QCoreApplication>
#include <QDataStream>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QDirIterator>
#include <QElapsedTimer>
#include <QFile>
#include <QFileInfo>
#include <QFuture>
#include <QHash>
#include <QHostAddress>
#include <QHostInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QList>
#include <QLocale>
#include <QMap>
#include <QMetaEnum>
#include <QMetaObject>
#include <QMetaType>
#include <QMimeDatabase>
#include <QMutex>
#include <QMutexLocker>
#include <QNetworkCookie>
#include <QNetworkInterface>
#include <QNetworkProxy>
#include <QNetworkReply>
#include <QObject>
#include <QPointer>
#include <QProcess>
#include <QPromise>
#include <QQueue>
#include <QReadWriteLock>
#include <QRegularExpression>
#include <QScopeGuard>
#include <QSet>
#include <QSettings>
#include <QSharedData>
#include <QSharedDataPointer>
#include <QSslCertificate>
#include <QSslKey>
#include <QSslSocket>
#include <QString>
#include <QStringList>
#include <QStringView>
#include <QTcpSocket>
#include <QThread>
#include <QThreadPool>
#include <QTime>
#include <QTimer>
#include <QUrl>
#include <QUrlQuery>
#include <QUuid>
#include <QVariant>
#include <QVariantHash>
#include <Qt>
#include <QtAssert>
#include <QtContainerFwd>
#include <QtLogging>
#include <QtSystemDetection>
#include <QtTypes>

// libtorrent
#include <libtorrent/fwd.hpp>
#include <libtorrent/extensions.hpp>
#include <libtorrent/session.hpp>

// std
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <cctype>
#include <chrono>
#include <cmath>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <ctime>
#include <exception>
#include <expected>
#include <filesystem>
#include <functional>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <memory>
#include <new>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <ranges>
#include <set>
#include <string>
#include <string_view>
#include <system_error>
#include <type_traits>
#include <utility>
#include <vector>

// boost
#include <boost/asio.hpp>
#include <boost/circular_buffer.hpp>

// Windows
#ifdef Q_OS_WIN
#include <windows.h>
#include <wincrypt.h>
#include <iphlpapi.h>
#endif

// Self
#include "bittorrent/addtorrentparams.h"
